exclude:
  - package.json
  - yarn.lock
  - postcss.config.js
  - tailwind.config.js
  - README.md
  - src/
defaults:
  - scope:
      path: ""
    values:
      layout: default
      title: Mayhem Robotics
